In [1]:
import pandas as pd


Q1. Student Performance DataFrame: Construction and Analysis
A college wants to analyze student performance using the following data.

In [2]:
data = { "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
        "Name": ["Amit", "Priya", "Rahul", "Neha", "Vikas", "Pooja", "Karan", "Simran", "Arjun", "Meena", "Rohit", "Anjali"],
         "Age": [19, 20, 18, 21, 20, 19, 22, 18, 21, 20, 19, 22],
         "Hours_Studied": [2, 5, 3, 8, 6, 4, 9, 2, 7, 5, 6, 8],
         "Attendance": [65, 85, 70, 95, 88, 75, 98, 60, 90, 82, 86, 94],
         "Marks": [48, 78, 55, 92, 84, 67, 96, 45, 89, 76, 81, 93] }

In [3]:
data

{'Student_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
 'Name': ['Amit',
  'Priya',
  'Rahul',
  'Neha',
  'Vikas',
  'Pooja',
  'Karan',
  'Simran',
  'Arjun',
  'Meena',
  'Rohit',
  'Anjali'],
 'Age': [19, 20, 18, 21, 20, 19, 22, 18, 21, 20, 19, 22],
 'Hours_Studied': [2, 5, 3, 8, 6, 4, 9, 2, 7, 5, 6, 8],
 'Attendance': [65, 85, 70, 95, 88, 75, 98, 60, 90, 82, 86, 94],
 'Marks': [48, 78, 55, 92, 84, 67, 96, 45, 89, 76, 81, 93]}

In [4]:
df = pd.DataFrame(data)
df

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [5]:
df.head()

   Student_ID   Name  Age  Hours_Studied  Attendance  Marks
0         101   Amit   19              2          65     48
1         102  Priya   20              5          85     78
2         103  Rahul   18              3          70     55
3         104   Neha   21              8          95     92
4         105  Vikas   20              6          88     84

In [6]:
df.tail(3)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [7]:
df.shape

(12, 6)

In [16]:
column_names = df.columns.tolist()
identifiers = ["Student_ID"]
categorical_attributes = ["Name"]
numerical_attributes = ["Age", "Hours_Studied", "Attendance", "Marks"]
print("Identifiers:", identifiers)
print("Categorical Attributes:", categorical_attributes)
print("Numerical Attributes:", numerical_attributes)

Identifiers: ['Student_ID']
Categorical Attributes: ['Name']
Numerical Attributes: ['Age', 'Hours_Studied', 'Attendance', 'Marks']

In [17]:

# Select Name, Hours_Studied, and Marks columns
selected_df = df[["Name", "Hours_Studied", "Marks"]]
print("Selected Columns:")
print(selected_df)

# Calculate average marks
average_marks = df["Marks"].mean()
print("\nAverage Marks:", average_marks)

# Filter students scoring above average
above_average = selected_df[selected_df["Marks"] > average_marks]

print("\nStudents Scoring Above Average:")
print(above_average)

Selected Columns:
      Name  Hours_Studied  Marks
0     Amit              2     48
1    Priya              5     78
2    Rahul              3     55
3     Neha              8     92
4    Vikas              6     84
5    Pooja              4     67
6    Karan              9     96
7   Simran              2     45
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

Average Marks: 75.33333333333333

Students Scoring Above Average:
      Name  Hours_Studied  Marks
1    Priya              5     78
3     Neha              8     92
4    Vikas              6     84
6    Karan              9     96
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

In [18]:
print("Before Resetting Index:")
print(above_average)
# Reset the index
reset_df = above_average.reset_index(drop=True)
print("\nAfter Resetting Index:")
print(reset_df)

Before Resetting Index:
      Name  Hours_Studied  Marks
1    Priya              5     78
3     Neha              8     92
4    Vikas              6     84
6    Karan              9     96
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

After Resetting Index:
     Name  Hours_Studied  Marks
0   Priya              5     78
1    Neha              8     92
2   Vikas              6     84
3   Karan              9     96
4   Arjun              7     89
5   Meena              5     76
6   Rohit              6     81
7  Anjali              8     93

Q2. Advanced Row and Column Selection Using iloc and loc

In [19]:
df

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [20]:
result = df.iloc[2:8][["Name", "Attendance", "Marks"]]

In [21]:
result

     Name  Attendance  Marks
2   Rahul          70     55
3    Neha          95     92
4   Vikas          88     84
5   Pooja          75     67
6   Karan          98     96
7  Simran          60     45

In [22]:
df_copy = df.copy()

df_copy = df_copy.set_index("Student_ID")

result = df_copy.loc[[103, 107, 110]]

In [23]:
result = df[ (df["Hours_Studied"] >= 6) & (df["Attendance"] >= 85) & (df["Marks"] > 80) ]

In [24]:
result

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
6          107   Karan   22              9          98     96
8          109   Arjun   21              7          90     89
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [25]:
result = df.iloc[-4:, -3:]
result

    Hours_Studied  Attendance  Marks
8               7          90     89
9               5          82     76
10              6          86     81
11              8          94     93

In [26]:

median_marks = df["Marks"].median()
print("Median Marks:", median_marks)

result = df[df["Marks"] < median_marks].copy()
print("\nStudents scoring below the median:")

reset_result = result.reset_index(drop=True)
print("\nAfter resetting the index:")

Median Marks: 79.5

Students scoring below the median:

After resetting the index:

Q3. Series vs. DataFrame: Feature Selection and Validation

In [27]:
df = pd.DataFrame({
    "Student_ID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95],
    "Sleep_Hours": [8, 7, 8, 6, 7, 6, 7, 8, 6, 7],
    "Marks": [35, 40, 48, 52, 61, 68, 74, 82, 90, 96]
})

In [28]:
df

   Student_ID  Hours_Studied  Attendance  Sleep_Hours  Marks
0         201              1          50            8     35
1         202              2          55            7     40
2         203              3          60            8     48
3         204              4          65            6     52
4         205              5          70            7     61
5         206              6          75            6     68
6         207              7          80            7     74
7         208              8          85            8     82
8         209              9          90            6     90
9         210             10          95            7     96

In [29]:
X_series = df["Hours_Studied"]
X_series

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Hours_Studied, dtype: int64

In [30]:
from os import X_OK
X_single = df[["Hours_Studied"]]
X_single

   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [31]:
y = df["Marks"]
y

0    35
1    40
2    48
3    52
4    61
5    68
6    74
7    82
8    90
9    96
Name: Marks, dtype: int64

In [32]:
X_single.shape

(10, 1)

In [33]:
X_series.shape

(10,)

In [34]:
y.shape

(10,)

In [35]:
print("\nX_series:")
print(X_series)
print("\nX_single:")
print(X_single)
print("\ny:")
print(y)

X_series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Hours_Studied, dtype: int64

X_single:
   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

y:
0    35
1    40
2    48
3    52
4    61
5    68
6    74
7    82
8    90
9    96
Name: Marks, dtype: int64

In [36]:

# Select three predictive features
X_multi = df[["Hours_Studied", "Attendance", "Sleep_Hours"]]

print("X_multi:")
print(X_multi)

print("\nFeature columns:", X_multi.columns.tolist())

# Verify excluded columns
print("\nIs Marks present?", "Marks" in X_multi.columns)
print("Is Student_ID present?", "Student_ID" in X_multi.columns)

print("\nShape of X_multi:", X_multi.shape)

X_multi:
   Hours_Studied  Attendance  Sleep_Hours
0              1          50            8
1              2          55            7
2              3          60            8
3              4          65            6
4              5          70            7
5              6          75            6
6              7          80            7
7              8          85            8
8              9          90            6
9             10          95            7

Feature columns: ['Hours_Studied', 'Attendance', 'Sleep_Hours']

Is Marks present? False
Is Student_ID present? False

Shape of X_multi: (10, 3)

In [37]:
X = df.drop(columns=["Marks", "Student_ID"])
print("Feature matrix X:")
print(X)

Feature matrix X:
   Hours_Studied  Attendance  Sleep_Hours
0              1          50            8
1              2          55            7
2              3          60            8
3              4          65            6
4              5          70            7
5              6          75            6
6              7          80            7
7              8          85            8
8              9          90            6
9             10          95            7

In [39]:
y = df["Marks"]
print("\nTarget variable y:")
print(y)
print("\nIs Marks in X?", "Marks" in X.columns)
print("Is Student_ID in X?", "Student_ID" in X.columns)

Target variable y:
0    35
1    40
2    48
3    52
4    61
5    68
6    74
7    82
8    90
9    96
Name: Marks, dtype: int64

Is Marks in X? False
Is Student_ID in X? False

In [41]:
assert len(X) == len(y)
assert X.shape[1] == 3
assert y.ndim == 1
print("Number of observations in X:", X.shape[0])
print("Number of observations in y:", y.shape[0])
print("Number of features in X:", X.shape[1])
print("Dimensions of y:", y.ndim)

Number of observations in X: 10
Number of observations in y: 10
Number of features in X: 3
Dimensions of y: 1

In [44]:
X_without_id = df[["Hours_Studied", "Attendance", "Sleep_Hours"]]
X_with_id = df[["Student_ID", "Hours_Studied", "Attendance", "Sleep_Hours"]]
print(X_without_id.head())
print(X_with_id.head())
print("\nShape without Student_ID:", X_without_id.shape)
print("Shape with Student_ID:", X_with_id.shape)

   Hours_Studied  Attendance  Sleep_Hours
0              1          50            8
1              2          55            7
2              3          60            8
3              4          65            6
4              5          70            7
   Student_ID  Hours_Studied  Attendance  Sleep_Hours
0         201              1          50            8
1         202              2          55            7
2         203              3          60            8
3         204              4          65            6
4         205              5          70            7

Shape without Student_ID: (10, 3)
Shape with Student_ID: (10, 4)

Q4. End-to-End Data Preparation Challenge
A training institute wants to predict students' final examination marks using their study behavior and attendance.

In [45]:

df = pd.DataFrame({
    "Student_ID": range(401, 421),
    "Name": list("ABCDEFGHIJKLMNOPQRST"),
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                      2, 4, 6, 8, 3, 5, 7, 9, 1, 10],
    "Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
                   58, 67, 78, 88, 62, 73, 83, 92, 52, 98],
    "Sleep_Hours": [5, 6, 7, 8, 6, 7, 8, 5, 6, 7,
                    8, 5, 6, 7, 8, 6, 7, 5, 6, 8],
    "Final_Marks": [30, 38, 45, 52, 60, 67, 75, 83, 90, 98,
                    40, 54, 70, 87, 48, 63, 78, 92, 34, 96]
})

def inspect_dataframe(dataframe):
    print("Number of rows:", dataframe.shape[0])
    print("Number of columns:", dataframe.shape[1])

    print("\nColumn names:")
    print(dataframe.columns.tolist())

    print("\nData types:")
    print(dataframe.dtypes)

    print("\nMissing values:")
    print(dataframe.isnull().sum())

inspect_dataframe(df)

Number of rows: 20
Number of columns: 6

Column names:
['Student_ID', 'Name', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Final_Marks']

Data types:
Student_ID        int64
Name             object
Hours_Studied     int64
Attendance        int64
Sleep_Hours       int64
Final_Marks       int64
dtype: object

Missing values:
Student_ID       0
Name             0
Hours_Studied    0
Attendance       0
Sleep_Hours      0
Final_Marks      0
dtype: int64

In [46]:

X_single = df[["Hours_Studied"]]
y = df["Final_Marks"]

X_multi = df[["Hours_Studied", "Attendance", "Sleep_Hours"]]

print("Single-feature X shape:", X_single.shape)
print("Multi-feature X shape:", X_multi.shape)
print("Target y shape:", y.shape)

print("\nSingle-feature columns:")
print(X_single.columns.tolist())

print("\nMulti-feature columns:")
print(X_multi.columns.tolist())

Single-feature X shape: (20, 1)
Multi-feature X shape: (20, 3)
Target y shape: (20,)

Single-feature columns:
['Hours_Studied']

Multi-feature columns:
['Hours_Studied', 'Attendance', 'Sleep_Hours']

In [47]:

low_attendance = df[df["Attendance"] < 70]

result = low_attendance[["Name", "Student_ID", "Final_Marks"]]

print(result)

   Name  Student_ID  Final_Marks
0     A         401           30
1     B         402           38
2     C         403           45
3     D         404           52
10    K         411           40
11    L         412           54
14    O         415           48
18    S         419           34

In [48]:

from sklearn.model_selection import train_test_split


X = df[["Hours_Studied", "Attendance", "Sleep_Hours"]]
y = df["Final_Marks"]


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


assert set(X_train.index).isdisjoint(set(X_test.index))

assert len(X_train) == len(y_train)
assert len(X_test) == len(y_test)
assert X_train.shape[1] == X_test.shape[1] == 3

print("\nAll validation checks passed!")

X_train shape: (16, 3)
X_test shape: (4, 3)
y_train shape: (16,)
y_test shape: (4,)

All validation checks passed!

In [50]:

import pandas as pd
from sklearn.model_selection import train_test_split


df = pd.DataFrame({
    "Student_ID": range(401, 421),
    "Name": list("ABCDEFGHIJKLMNOPQRST"),
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                      2, 4, 6, 8, 3, 5, 7, 9, 1, 10],
    "Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
                   58, 67, 78, 88, 62, 73, 83, 92, 52, 98],
    "Sleep_Hours": [5, 6, 7, 8, 6, 7, 8, 5, 6, 7,
                    8, 5, 6, 7, 8, 6, 7, 5, 6, 8],
    "Final_Marks": [30, 38, 45, 52, 60, 67, 75, 83, 90, 98,
                    40, 54, 70, 87, 48, 63, 78, 92, 34, 96]
})

feature_columns = [
    "Hours_Studied",
    "Attendance",
    "Sleep_Hours"
]
target_column = "Final_Marks"

required_columns = feature_columns + [target_column]

assert all(col in df.columns for col in required_columns), \
    "Required columns are missing."

assert not df[required_columns].isnull().any().any(), \
    "Missing values found in features or target."


X = df[feature_columns]
y = df[target_column]


assert len(X) == len(y), "X and y have different row counts."
assert X.shape[1] == 3, "Expected exactly 3 features."
assert y.ndim == 1, "Target must be one-dimensional."


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)


assert set(X_train.index).isdisjoint(set(X_test.index))
assert len(X_train) == len(y_train)
assert len(X_test) == len(y_test)


print("DATA PREPARATION REPORT")
print("-----------------------")
print("Total observations:", len(df))
print("Number of features:", X.shape[1])
print("Feature columns:", X.columns.tolist())
print("Target column:", target_column)
print("Missing values in selected columns:",
      df[required_columns].isnull().sum().sum())

print("\nTraining feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

print("\nAll validation checks passed!")

DATA PREPARATION REPORT
-----------------------
Total observations: 20
Number of features: 3
Feature columns: ['Hours_Studied', 'Attendance', 'Sleep_Hours']
Target column: Final_Marks
Missing values in selected columns: 0

Training feature shape: (16, 3)
Testing feature shape: (4, 3)
Training target shape: (16,)
Testing target shape: (4,)

All validation checks passed!